### ISSUE TITLE
cursor animation only works in vim mode

### ISSUE THREAD

**Issue by RMHogervorst** [gadenbuie/yule-rstudio#2]
Very cool theme Garrick! 
Unfortunately the cursor animation only works in vim mode. too bad!

**Comment by gadenbuie** [comment]
I made the regular cursor do the cool color change thing as well. The animation cycle is longer so that it doesn't get too distracting.

Update your theme:

```r
fs::file_delete(fs::path_home_r(".R", "rstudio", "themes", "Yule-RStudio.rstheme"))
yule_theme <- fs::path_temp("Yule-RStudio", ext = "rstheme")
download.file("https://git.io/yule-rstudio", yule_theme)
rstudioapi::addTheme(yule_theme, apply = TRUE)
```

**Comment by RMHogervorst** [comment]
You would not believe how much fun I have with this theme! Thanks!
