### ISSUE TITLE
Suggestion for .ace_invisible (whitespace characters)

### ISSUE THREAD

**Issue by hlynurhallgrims** [gadenbuie/yule-rstudio#4]
I've added a pull request that adds .ace_invisible so that whitespace characters are "less in-your-face". 

This is what it currently looks like.
![image](https://user-images.githubusercontent.com/6782760/70044962-34f8a700-15bb-11ea-9af3-3fa26387667c.png)

This is what it looks like with https://github.com/gadenbuie/yule-rstudio/pull/3
![image](https://user-images.githubusercontent.com/6782760/70045260-ad5f6800-15bb-11ea-8d62-2960a01990c5.png)

**Comment by gadenbuie** [comment]
Thanks for catching this and for the pull request! Happy holidays!

Oh and if you like RStudio themes check out https://github.com/gadenbuie/rsthemes/ ... I'm hoping to move this over into that collection soon.
